---
cache: bundler
os:
- linux
- osx
rvm:
- 2.0
- 2.1
- 2.2
- jruby-9.0.4.0
matrix:
  allow_failures:
  - rvm: jruby-9.0.4.0
notifications:
  email:
  - jordon@envygeeks.io
branches:
  only:
  - master
